# Generated by Django 4.2.11 on 2024-05-10 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0002_customer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="customer_points",
            new_name="customer_amount",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="customer_dob",
            new_name="customer_contact",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="customer_gender",
        ),
    ]
