# Generated by Django 4.2.11 on 2024-05-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0005_remove_product_product_unit_invoicedetail_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="gst",
            field=models.BooleanField(default=False, max_length=3),
        ),
    ]
