# Generated by Django 4.2.11 on 2024-05-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0006_invoice_gst"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_created=True)),
                ("expense", models.CharField(max_length=255)),
                ("cost", models.FloatField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
