# Generated by Django 4.2.11 on 2024-05-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0007_expense"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense",
            old_name="cost",
            new_name="expense_cost",
        ),
        migrations.RenameField(
            model_name="expense",
            old_name="is_active",
            new_name="expense_is_active",
        ),
        migrations.RenameField(
            model_name="expense",
            old_name="expense",
            new_name="expense_name",
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
