# Generated by Django 4.2.13 on 2024-05-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_invoice_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='price',
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
