# Generated by Django 4.2.13 on 2024-05-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_alter_invoice_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='invoicedetail_is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
