# Generated by Django 4.2.11 on 2024-06-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0015_alter_customer_customer_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Bank_name",
                    models.CharField(
                        choices=[
                            ("SBI", "State Bank of India"),
                            ("ICICI", "ICICI Bank"),
                        ],
                        default="SBI",
                        max_length=255,
                    ),
                ),
                ("Payment_cost", models.FloatField()),
                ("date", models.DateField(auto_now_add=True)),
                ("Payment_is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
